// This file is auto-generated by @hey-api/openapi-ts

export const ChallengeQuotaPublicSchema = {
    properties: {
        remaining_quota: {
            type: 'integer',
            minimum: 0,
            title: 'Remaining Quota',
            description: '剩余引用次数',
            default: 10
        },
        daily_quota: {
            type: 'integer',
            minimum: 0,
            title: 'Daily Quota',
            description: '每日配额',
            default: 10
        }
    },
    type: 'object',
    title: 'ChallengeQuotaPublic',
    description: '挑战配额响应模型。'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const OptionSchema = {
    properties: {
        option_index: {
            type: 'integer',
            title: 'Option Index'
        },
        option_text: {
            type: 'string',
            title: 'Option Text'
        }
    },
    type: 'object',
    required: [
        'option_index',
        'option_text'
    ],
    title: 'Option'
} as const;

export const QuestionDifficultySchema = {
    type: 'string',
    enum: [
        'easy',
        'medium',
        'hard'
    ],
    title: 'QuestionDifficulty'
} as const;

export const QuestionListSchema = {
    properties: {
        difficulty: {
            $ref: '#/components/schemas/QuestionDifficulty',
            description: '题目难度',
            default: 'easy'
        },
        question_description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Question Description',
            description: '简短描述'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            description: '创建时间'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id',
            description: '题目id'
        }
    },
    type: 'object',
    required: [
        'question_description',
        'id'
    ],
    title: 'QuestionList',
    description: '题目列表模型。'
} as const;

export const QuestionPublicSchema = {
    properties: {
        difficulty: {
            $ref: '#/components/schemas/QuestionDifficulty',
            description: '题目难度',
            default: 'easy'
        },
        question_description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Question Description',
            description: '简短描述'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            description: '创建时间'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id',
            description: '题目id'
        },
        options: {
            items: {
                $ref: '#/components/schemas/Option'
            },
            type: 'array',
            title: 'Options',
            description: '题目选项'
        },
        correct_option_index: {
            type: 'integer',
            title: 'Correct Option Index',
            description: '正确选项索引'
        },
        question_content: {
            type: 'string',
            maxLength: 1000,
            title: 'Question Content',
            description: '题目内容'
        },
        explanation: {
            type: 'string',
            title: 'Explanation',
            description: '解释'
        }
    },
    type: 'object',
    required: [
        'question_description',
        'id',
        'options',
        'correct_option_index',
        'question_content',
        'explanation'
    ],
    title: 'QuestionPublic',
    description: '题目公开响应模型。'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;
