// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { QuestionsCreateQuestionData, QuestionsCreateQuestionErrors, QuestionsCreateQuestionResponses, QuestionsReadQuestionData, QuestionsReadQuestionErrors, QuestionsReadQuestionResponses, QuestionsReadQuestionslistData, QuestionsReadQuestionslistResponses, QuotaReadQuotaData, QuotaReadQuotaResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class QuestionsService {
    /**
     * Read Questionslist
     *
     * 根据 user_id 查询题目列表。
     */
    public static readQuestionslist<ThrowOnError extends boolean = false>(options?: Options<QuestionsReadQuestionslistData, ThrowOnError>) {
        return (options?.client ?? client).get<QuestionsReadQuestionslistResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/questionsquestionlist',
            ...options
        });
    }
    
    /**
     * Read Question
     *
     * 根据 question_id 查询完整题目与答案。
     */
    public static readQuestion<ThrowOnError extends boolean = false>(options: Options<QuestionsReadQuestionData, ThrowOnError>) {
        return (options.client ?? client).get<QuestionsReadQuestionResponses, QuestionsReadQuestionErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/questions/{question_id}',
            ...options
        });
    }
    
    /**
     * Create Question
     *
     * 创建题目。
     */
    public static createQuestion<ThrowOnError extends boolean = false>(options: Options<QuestionsCreateQuestionData, ThrowOnError>) {
        return (options.client ?? client).post<QuestionsCreateQuestionResponses, QuestionsCreateQuestionErrors, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/questions/',
            ...options
        });
    }
}

export class QuotaService {
    /**
     * Read Quota
     *
     * 根据 user_id 查询配额。
     */
    public static readQuota<ThrowOnError extends boolean = false>(options?: Options<QuotaReadQuotaData, ThrowOnError>) {
        return (options?.client ?? client).get<QuotaReadQuotaResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/api/v1/quota/quota',
            ...options
        });
    }
}
