// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * ChallengeQuotaPublic
 *
 * 挑战配额响应模型。
 */
export type ChallengeQuotaPublic = {
    /**
     * Remaining Quota
     *
     * 剩余引用次数
     */
    remaining_quota?: number;
    /**
     * Daily Quota
     *
     * 每日配额
     */
    daily_quota?: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Option
 */
export type Option = {
    /**
     * Option Index
     */
    option_index: number;
    /**
     * Option Text
     */
    option_text: string;
};

/**
 * QuestionDifficulty
 */
export type QuestionDifficulty = 'easy' | 'medium' | 'hard';

/**
 * QuestionList
 *
 * 题目列表模型。
 */
export type QuestionList = {
    /**
     * 题目难度
     */
    difficulty?: QuestionDifficulty;
    /**
     * Question Description
     *
     * 简短描述
     */
    question_description: string | null;
    /**
     * Created At
     *
     * 创建时间
     */
    created_at?: string;
    /**
     * Id
     *
     * 题目id
     */
    id: string;
};

/**
 * QuestionPublic
 *
 * 题目公开响应模型。
 */
export type QuestionPublic = {
    /**
     * 题目难度
     */
    difficulty?: QuestionDifficulty;
    /**
     * Question Description
     *
     * 简短描述
     */
    question_description: string | null;
    /**
     * Created At
     *
     * 创建时间
     */
    created_at?: string;
    /**
     * Id
     *
     * 题目id
     */
    id: string;
    /**
     * Options
     *
     * 题目选项
     */
    options: Array<Option>;
    /**
     * Correct Option Index
     *
     * 正确选项索引
     */
    correct_option_index: number;
    /**
     * Question Content
     *
     * 题目内容
     */
    question_content: string;
    /**
     * Explanation
     *
     * 解释
     */
    explanation: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type QuestionsReadQuestionslistData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/questionsquestionlist';
};

export type QuestionsReadQuestionslistResponses = {
    /**
     * Response Questions-Read Questionslist
     *
     * Successful Response
     */
    200: Array<QuestionList>;
};

export type QuestionsReadQuestionslistResponse = QuestionsReadQuestionslistResponses[keyof QuestionsReadQuestionslistResponses];

export type QuestionsReadQuestionData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/api/v1/questions/{question_id}';
};

export type QuestionsReadQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QuestionsReadQuestionError = QuestionsReadQuestionErrors[keyof QuestionsReadQuestionErrors];

export type QuestionsReadQuestionResponses = {
    /**
     * Successful Response
     */
    200: QuestionPublic;
};

export type QuestionsReadQuestionResponse = QuestionsReadQuestionResponses[keyof QuestionsReadQuestionResponses];

export type QuestionsCreateQuestionData = {
    body?: never;
    path?: never;
    query: {
        difficulty: QuestionDifficulty;
    };
    url: '/api/v1/questions/';
};

export type QuestionsCreateQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QuestionsCreateQuestionError = QuestionsCreateQuestionErrors[keyof QuestionsCreateQuestionErrors];

export type QuestionsCreateQuestionResponses = {
    /**
     * Successful Response
     */
    200: QuestionPublic;
};

export type QuestionsCreateQuestionResponse = QuestionsCreateQuestionResponses[keyof QuestionsCreateQuestionResponses];

export type QuotaReadQuotaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/quota/quota';
};

export type QuotaReadQuotaResponses = {
    /**
     * Successful Response
     */
    200: ChallengeQuotaPublic;
};

export type QuotaReadQuotaResponse = QuotaReadQuotaResponses[keyof QuotaReadQuotaResponses];
